Given the list of original regions, we asked ChatGPT (GPT-4o) to extract for each of them the Nominatim API query to extract the point coordinates and the bounding box coordinates. 

In this file we execute the API calls to obtain the coordinates for each region. If for some region the API call fails, we inspect these cases manually.


CASI STRANI IDENTIFICATI: 

Central Chile ritorna una stazione di servizio che sta all'estremo nord del Chile.

In [1]:
import pandas as pd
import requests
import time
import numpy as np
import math
import matplotlib.pyplot as plt

In [2]:
COMPLETE_REGION_DATASET_PATH = './support_files/Complete_Region_Dataset.csv' #obtained with GPT-4o
COMPLETE_REGION_DATASET_UPDATED_PATH = './support_files/Updated_Complete_Region_Dataset.csv' #save the updated dataframe generated by us

In [ ]:
def obtain_coordinates(url: str) -> tuple[float, float, list, float]:
    """For each region, from the url of the API call to OpenStreetMap obtain the point coordinates and the bounding box coordinates"""

    # url = "https://nominatim.openstreetmap.org/search?country=Yemen&format=json&limit=1"

    # Send the GET request
    response = requests.get(url, headers={'User-Agent': 's319848@studenti.polito.it'})

    # Handle the response
    if response.status_code == 200:
        data = response.json()

        if data != []:
            lat = float(data[0]['lat']) #point coordinate for latitude of the region
            lon = float(data[0]['lon']) #point coordinate for longitude of the region
            bbox_str = data[0]['boundingbox'] #bounding box for the region (originally list of strings)
            bbox = [float(x) for x in bbox_str]
            area = abs(bbox[1] - bbox[0]) * abs(bbox[3] - bbox[2])

        else:
            print(f"Region not found for url = {url}")
            return (None, None, None, None)

        return (lat, lon, bbox, area)
    else:
        print(f"url: {url} \nError:", response.status_code)
        return (None, None, None, None)

In [ ]:
def fill_dataset(regions_path: str) -> pd.DataFrame:
    """Take the incomplete dataset and fill it with the coordinates by calling the API with the correct url"""

    regions_df = pd.read_csv(regions_path)

    for i, row in regions_df.iterrows():

        url = row['Nominatim URL']

        (lat, lon, bbox, area) = obtain_coordinates(url)

        regions_df.at[i, 'lat'] = lat
        regions_df.at[i, 'lon'] = lon
        regions_df.at[i, 'bbox'] = ''
        regions_df.at[i, 'bbox'] = bbox
        regions_df.at[i, 'area'] = area

        time.sleep(1)

    return regions_df

    #obtain the tuple (lat, lon, bbox) with the function obtain_coordinates, plug it in the dataset. Manually identify absent cases

In [65]:
regions_df_complete = fill_dataset(COMPLETE_REGION_DATASET_PATH)
regions_df_complete.to_csv(COMPLETE_REGION_DATASET_UPDATED_PATH, index=False)
regions_df_complete

Region not found for url = https://nominatim.openstreetmap.org/search?q=Northeastern%20Argentina&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Northwestern%20Argentina&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Southern%20Argentina&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Cape+Provinces+South+Africa&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Central+European+Russia&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Northern+Chile&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=North-Central+China&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Czech+Republic+and+Slovakia&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=East+Aegean+Islands+Greece&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Northwestern+Balkan+Peninsula&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=North+European+Russia&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Northwest+European+Russia&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?country=Palestine&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=South+European+Russia&format=json&limit=1
Region not found for url = https://nominatim.openstreetmap.org/search?q=Transcaucasia&format=json&limit=1

,Original name,Entire name,OSM Tags,Nominatim URL,lat,lon,bbox,area
0,Afghanistan,Islamic Republic of Afghanistan,"boundary=administrative, admin_level=2",https://nominatim.openstreetmap.org/search?cou...,33.768006,66.238514,"[29.3772926, 38.4910682, 60.5176034, 74.889862]",130.985540
1,Alabama,State of Alabama (USA),"boundary=administrative, admin_level=4",https://nominatim.openstreetmap.org/search?cou...,33.258882,-86.829534,"[30.143376, 35.0081121, -88.4731014, -84.8882885]",17.439169
2,Alaska,State of Alaska (USA),"boundary=administrative, admin_level=4",https://nominatim.openstreetmap.org/search?cou...,64.445961,-149.680909,"[51.0070029, 71.5889534, -180.0, 180.0]",7409.502180
3,Albania,Republic of Albania,"boundary=administrative, admin_level=2",https://nominatim.openstreetmap.org/search?cou...,41.000028,19.999962,"[39.640394, 42.6610848, 19.0009866, 21.0574335]",6.211890
4,Alberta,Province of Alberta (Canada),"boundary=administrative, admin_level=4",https://nominatim.openstreetmap.org/search?cou...,55.001251,-115.002136,"[48.9966667, 60.0004699, -120.0013835, -110.00...",110.000835
...,...,...,...,...,...,...,...,...
190,Western Australia,State of Western Australia (Australia),"boundary=administrative, admin_level=4",https://nominatim.openstreetmap.org/search?cou...,-25.230300,121.018725,"[-35.2418503, -13.5076852, 112.8656697, 129.00...",350.710723
191,Wisconsin,State of Wisconsin (USA),"boundary=administrative, admin_level=4",https://nominatim.openstreetmap.org/search?cou...,44.430898,-89.688464,"[42.4919515, 47.3025, -92.8893149, -86.249548]",31.940921
192,Wyoming,State of Wyoming (USA),"boundary=administrative, admin_level=4",https://nominatim.openstreetmap.org/search?cou...,43.170026,-107.568534,"[40.9948223, 45.0058281, -111.0552665, -104.05...",28.089129
193,Xinjiang,Xinjiang Uyghur Autonomous Region (China),"boundary=administrative, admin_level=4",https://nominatim.openstreetmap.org/search?q=X...,42.480495,85.463346,"[34.3340633, 49.1780565, 73.4997347, 96.3874094]",339.744488
194,Yemen,Republic of Yemen,"boundary=administrative, admin_level=2",https://nominatim.openstreetmap.org/search?cou...,16.347124,47.891527,"[11.9084802, 19.0, 41.60825, 54.7389375]",93.116530

In [66]:
georgia_coordinates = obtain_coordinates("https://nominatim.openstreetmap.org/search?country=USA&state=Georgia&format=json&limit=1")

print(type(georgia_coordinates[0]))
print(georgia_coordinates)

<class 'float'>
(32.3293809, -83.1137366, [30.3556558, 35.0006769, -85.605165, -80.751429], 22.545706133829594)

After completing the dataset with the bounding boxes, we check for which of the regions OSM got it wrong, identifying a point location instead of a region. First we compute the distribution of the areas.

In [3]:
regions_df_complete = pd.read_csv(COMPLETE_REGION_DATASET_UPDATED_PATH)

areas_list = regions_df_complete['area'].to_list()
clean_list = [x for x in areas_list if not math.isnan(x)]

# plt.hist(clean_list, bins=190)
percentile_5 = np.percentile(clean_list, q=5, method='nearest')
percentile_10 = np.percentile(clean_list, q=10, method='nearest')
percentile_15 = np.percentile(clean_list, q=15, method='nearest')
percentile_20 = np.percentile(clean_list, q=20, method='nearest')

print(f"Total number of clean areas: {len(clean_list)}")

print(f"Number of elements under the 5th percentile ({percentile_5}) : {len([x for x in clean_list if x<percentile_5])}")
print(f"Region corresponding to 5th percentile: {regions_df_complete[regions_df_complete['area']==percentile_5]['Original name']}\n")

print(f"Number of elements under the 10th percentile ({percentile_10}) : {len([x for x in clean_list if x<percentile_10])}")
print(f"Region corresponding to 10th percentile: {regions_df_complete[regions_df_complete['area']==percentile_10]['Original name']}\n")
#10th percentile is Norfolk Islands, which is an actual region
#We look around (up and down) Norfolk Islands to see when actually regions become points.

Total number of clean areas: 180
Number of elements under the 5th percentile (6.259318299995982e-06) : 9
Region corresponding to 5th percentile: 33    China South-Central
Name: Original name, dtype: object

Number of elements under the 10th percentile (0.293685889621084) : 18
Region corresponding to 10th percentile: 121    Norfolk Is.
Name: Original name, dtype: object

In [97]:
regions_df_complete.sort_values(by='area', ascending=True)

,Original name,Entire name,OSM Tags,Nominatim URL,lat,lon,bbox,area
20,Brazil South,Southern Region of Brazil,place=region,https://nominatim.openstreetmap.org/search?q=S...,40.458606,19.466956,"[40.4585559, 40.4586559, 19.4669059, 19.4670059]",1.000000e-08
187,West Himalaya,Western Himalaya,place=region,https://nominatim.openstreetmap.org/search?q=W...,52.364680,4.861675,"[52.3646302, 52.3647302, 4.8616252, 4.8617252]",1.000000e-08
97,Mexico Gulf,Gulf Region of Mexico,place=region,https://nominatim.openstreetmap.org/search?q=G...,25.283446,-89.906616,"[25.2833959, 25.2834959, -89.9066663, -89.9065...",1.000000e-08
86,Lebanon-Syria,Lebanon and Syria,place=region,https://nominatim.openstreetmap.org/search?q=L...,34.000000,36.500000,"[33.99995, 34.00005, 36.49995, 36.50005]",1.000000e-08
188,West Siberia,Western Siberia (Russia),place=region,https://nominatim.openstreetmap.org/search?q=W...,62.000000,76.000000,"[61.99995, 62.00005, 75.99995, 76.00005]",1.000000e-08
...,...,...,...,...,...,...,...,...
125,North European Russia,Northern European Russia,place=region,https://nominatim.openstreetmap.org/search?q=N...,NaN,NaN,None,NaN
127,Northwest European Russia,Northwestern European Russia,place=region,https://nominatim.openstreetmap.org/search?q=N...,NaN,NaN,None,NaN
135,Palestine,State of Palestine,"boundary=administrative, admin_level=2",https://nominatim.openstreetmap.org/search?cou...,NaN,NaN,None,NaN
160,South European Russia,Southern European Russia,place=region,https://nominatim.openstreetmap.org/search?q=S...,NaN,NaN,None,NaN
171,Transcaucasus,Transcaucasia,place=region,https://nominatim.openstreetmap.org/search?q=T...,NaN,NaN,None,NaN

By manually inspecting the dataframe, sorting area by ascending values, we can see that the first region with a small area but which is a correct region is the region of District of Columbia (index = 45).
Everything below that value (16 regions) is a wrong region, as can be seen by looking at which regions report these values.